<?php

function pivot_dml_menu() {

  $path = variable_get('pivot_dml_path', '');
  if(!empty($path)) {
    $items[$path.'/about'] = array(
      'page callback' => 'pivot_dml_about_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/ad'] = array(
      'page callback' => 'pivot_dml_ad_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/news'] = array(
      'page callback' => 'pivot_dml_news_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/quiz'] = array(
      'page callback' => 'pivot_dml_quiz_view',
      'access arguments' => array('access content'),
    );
  }
  return $items;
}
function pivot_dml_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id)  {
    case 'pivot_campaign_config':
      $form['pivot_dml_path'] = array (
        '#type' => 'textfield',
        '#title' => t('DML Path'),
        '#description' => t("Path with no leading or trailing slash.  Example 'campaign/dml"),
        '#required' => TRUE,
        '#default_value' => variable_get('pivot_dml_path', ''),
      );
    break;
  }
}

function pivot_dml_about_view(){
  $output = theme('pivot_dml_about');
  return $output;
}
function pivot_dml_ad_view(){
  $output = theme('pivot_dml_ad');
  return $output;
}
function pivot_dml_news_view(){
  $output = theme('pivot_dml_news');
  return $output;
}
function pivot_dml_quiz_view(){
  $output = theme('pivot_dml_quiz');
  return $output;
}
function pivot_dml_default_view(){
  $output = theme('pivot_dml_default');
  return $output;
}

function pivot_dml_theme() {
  return array(
    'pivot_dml_about' => array(
      'arguments' => array(),
      'template' => 'templates/piv-dml-about'
    ),
    'pivot_dml_ad' => array(
      'arguments' => array(),
      'template' => 'templates/piv-dml-ad'
    ),
    'pivot_dml_news' => array(
      'arguments' => array(),
      'template' => 'templates/piv-dml-news'
    ),
    'pivot_dml_quiz' => array(
      'arguments' => array(),
      'template' => 'templates/piv-dml-quiz'
    ),
    'pivot_dml_default' => array(
      'arguments' => array(),
      'template' => 'templates/piv-dml-default'
    ),
  );
}




function pivot_dml_preprocess_node(&$variables){
  $variables['theme_hook_suggestions'][] = 'node__piv_dml';
}

/**
 * Move node template file to module directory
**/
function pivot_dml_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'pivot_dml');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pivot', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _pivot_dml_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}
function _pivot_dml_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

