<?php
/**
 * @file
 * Module to add HTML title option to menu item links.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function menu_html_form_menu_edit_item_alter(&$form, $form_state) {
  $item = $form['original_item']['#value'];
  $form['html_title'] = array(
    '#type' => 'checkbox',
    '#title' => t('HTML Title'),
    '#default_value' => isset($item['options']['html']) ? $item['options']['html'] : 0,
    '#description' => t('Allow HTML in the menu link title.'),
    '#weight' => -1,
  );
  $form['link_title']['#weight'] = -2;
}

/**
 * Implements hook_menu_link_alter()
 */
function menu_html_menu_link_alter(&$item) {
  if (isset($item['html_title']) && $item['html_title']) {
    $item['options']['html'] = $item['html_title'];
  }
  else {
    unset($item['options']['html']);
  }
  unset($item['html_title']);
}
