<?php
/**
 * @file
 * pivot_interstitial.module
 */

/**
 * Implements hook_menu();
 */
function pivot_interstitial_menu(){
	$items = array();
	$items['interstitial/channelFinder'] = array(
		'title' => t('Channel Finder Interstitial'),
		'page callback' => 'pivot_interstitial_channel_finder',
		'access arguments' => array('access content')
	);

	return $items;
}

function pivot_interstitial_channel_finder(){
	drupal_add_library('system', 'jquery.cookie');
	$block = module_invoke('pivot_global', 'block_view', 'find_pivot_sidebar');
	$pivot_channel_finder = $block['content'];
	$block = theme('interstitial_cf', array('pivot_channel_finder' => $pivot_channel_finder));
	return $block;
}

/**
 * Implements hook_theme
 */
function pivot_interstitial_theme(){
	return array(
		'interstitial_cf' => array(
			'variables' => array(
				'pivot_channel_finder' => array()
			),
			'template' => 'pivot-interstitial-channel-finder',
		)
	);
}