<?php
/**
 * @file
 * pivot_interstitial.module
 */

/**
 * Implements hook_menu();
 */
function pivot_interstitial_menu(){
	$items = array();
	$items['interstitial/channelFinder'] = array(
		'title' => t('Channel Finder Interstitial'),
		'page callback' => 'pivot_interstitial_channel_finder',
		'access arguments' => array('access content')
	);

	return $items;
}

function pivot_interstitial_channel_finder(){
	$block = module_invoke('pivot_global', 'block_view', 'find_pivot_sidebar');
	$pivot_channel_finder = $block['content'];
	drupal_add_css(drupal_get_path('module', 'pivot_interstitial'). '/css/interstitial.css');
	$block = theme('interstitial_cf', array('pivot_channel_finder' => $pivot_channel_finder));
	return $block;
}

/**
 * Implements hook_theme
 */
function pivot_interstitial_theme(){
	return array(
		'interstitial_cf' => array(
			'variables' => array(
				'pivot_channel_finder' => array()
			),
			'template' => 'pivot-interstitial-channel-finder',
		)
	);
}

/**
 * Implements hook_init
 */
function pivot_interstitial_init(){
	drupal_add_library('system', 'jquery.cookie');
}

/**
 *	Implements hook_preprocess_html().
 */
function pivot_interstitial_preprocess_html(&$vars) {
	//only does this on interstitial channel finder page
	if (arg(0) == 'interstitial' && arg(1) == 'channelFinder') {
		//changes s.t to s.tl as it's provided from sitecatalyst
		$tl_version = $vars['page']['page_bottom']['sitecatalyst']['footer']['#markup'];
		$tl_version = str_replace('s.t(', 's.tl(', $tl_version);
		$vars['page']['page_bottom']['sitecatalyst']['footer']['#markup'] = $tl_version;
	}
}