<?php

function pivot_dml_menu() {

  $items['admin/config/campaign/dml'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pivot_dml_config_view'),
    'access arguments' => array('administer nodes'),
  );
  $path = variable_get('pivot_dml_path', '');
  if(!empty($path)) {
    $items[$path.'/about'] = array(
      'page callback' => 'pivot_dml_about_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/ad'] = array(
      'page callback' => 'pivot_dml_ad_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/news'] = array(
      'page callback' => 'pivot_dml_news_view',
      'access arguments' => array('access content'),
    );
    $items[$path.'/quiz'] = array(
      'page callback' => 'pivot_dml_quiz_view',
      'access arguments' => array('access content'),
    );
  }
  return $items;
}
function pivot_dml_config_view(){
  $form['pivot_dml_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Campaign Page Path'),
    '#description' => t("Path with no leading or trailing slash.  Example 'campaign/dml"),
    '#required' => TRUE,
    '#default_value' => variable_get('pivot_dml_path', ''),
  );

  $form = system_settings_form($form);
  return $form;
}
function pivot_dml_about_view(){
  theme('pivot_dml_about', $args);
}
function pivot_dml_ad_view(){
  theme('pivot_dml_ad', $args);
}
function pivot_dml_news_view(){
  theme('pivot_dml_news', $args);
}
function pivot_dml_quiz_view(){
  theme('pivot_dml_quiz', $args);
}
function pivot_dml_default_view(){
  theme('pivot_dml_default', $args);
}

function pivot_dml_theme() {
  return array(
    'pivot_dml_about' => array(
      'arguments' => array(),
      'template' => 'piv-dml-about'
    ),
    'pivot_dml_ad' => array(
      'arguments' => array(),
      'template' => 'piv-dml-ad'
    ),
    'pivot_dml_news' => array(
      'arguments' => array(),
      'template' => 'piv-dml-news'
    ),
    'pivot_dml_quiz' => array(
      'arguments' => array(),
      'template' => 'piv-dml-quiz'
    ),
    'pivot_dml_default' => array(
      'arguments' => array(),
      'template' => 'piv-dml-default'
    ),
  );
}




