<?php

define('DIGITAL_MEDIA_LITERACY_BASE_PATH', 'dml');
define('DIGITAL_MEDIA_LITERACY_THEME_PATH', 'sites/all/themes/pivot/templates/dml');

function pivot_dml_menu() {

  return array(
    DIGITAL_MEDIA_LITERACY_BASE_PATH => array(
      'title' => 'Digital Media Literacy',
      'page callback' => 'pivot_dml_page_callback',
      'access arguments' => array('access content'),
    ),
    DIGITAL_MEDIA_LITERACY_BASE_PATH . '/quiz' => array(
      'title' => 'Digital Media Literacy - Quiz',
      'page callback' => 'pivot_dml_page_callback',
      'access arguments' => array('access content'),
    ),
    DIGITAL_MEDIA_LITERACY_BASE_PATH . '/ad' => array(
      'title' => 'Digital Media Literacy - Ad',
      'page callback' => 'pivot_dml_page_callback',
      'access arguments' => array('access content'),
    ),
    DIGITAL_MEDIA_LITERACY_BASE_PATH . '/news' => array(
      'title' => 'Digital Media Literacy - News',
      'page callback' => 'pivot_dml_page_callback',
      'access arguments' => array('access content'),
    ),
    DIGITAL_MEDIA_LITERACY_BASE_PATH . '/about' => array(
      'title' => 'Digital Media Literacy - About',
      'page callback' => 'pivot_dml_page_callback',
      'access arguments' => array('access content'),
    ),
  );
}

function pivot_dml_page_callback() {
  // The template handles all the markup
  return '';
}

function pivot_dml_get_path($item) {

  switch ($item) {

    case 'js':
      return DIGITAL_MEDIA_LITERACY_THEME_PATH . '/public/js';
    case 'css':
      return DIGITAL_MEDIA_LITERACY_THEME_PATH . '/public/css';
    case 'images':
      return DIGITAL_MEDIA_LITERACY_THEME_PATH . '/public/images';
    case 'templates':
      return DIGITAL_MEDIA_LITERACY_THEME_PATH;
  }
}

function pivot_dml_get_root_path() {
  return '/pivot/pivot-tv/drupal';
}

