<?php
/**
 * @file
 * A module defining custom functionality for the Pivot.tv website
 *
 */
/**
 * Implements hook_help();
 */
function pivot_global_help($path, $arg) {
    if ($path == 'admin/help#pivot_global') {
        return t('A module defining custom functionality for the Pivot.tv website');
    }
}
/**
 * Define custom blocks for the Pivot.tv site
 */
include 'pivot_global.blocks.inc';

/**
* Implements hook_entity_info_alter().
*/
function pivot_global_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['promo'] = array(
    'label' => t('Promo'),
    'custom settings' => TRUE,
  );
}

/**
* Prevent Drupal from checking for updates on custom created modules
**/
function pivot_global_update_projects_alter(&$projects) {
  unset($projects['pivot_global']);
  unset($projects['pivot_campaign']);
  unset($projects['pivot_hero']);
  unset($projects['pivot_dml']);
}
/**
* Implements hook_preprocess_node().
*/
function pivot_global_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'promo') {
    // add classes to promo <article>s
    $vars['classes_array'][] = 'promo';
    $vars['classes_array'][] = 'node-' . $vars['type'] . '-promo';

    // use our custom templates for easy overridability
    $vars['theme_hook_suggestions'][] = 'node__promo';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__promo';

    // write an external link tag if any
    $vars['promo_external_anchor_tag'] = '';
    if ($vars['field_external_link'] && $vars['field_external_link']['und'][0]['url']) {
      $vars['promo_external_anchor_tag'] .= '<a href="' . $vars['field_external_link']['und'][0]['url'] . '"';
      if (isset($vars['field_external_link']['und'][0]['title'])) {
        $vars['promo_external_anchor_tag'] .= ' title="' . $vars['field_external_link']['und'][0]['title'] .'"';
      }
      if (isset($vars['field_external_link']['und'][0]['attributes']['target'])) {
        $vars['promo_external_anchor_tag'] .= ' target="' . $vars['field_external_link']['und'][0]['attributes']['target'] . '"';
      }
      $vars['promo_external_anchor_tag'] .= '>';
    }
  } else if ($vars['view_mode'] == 'teaser') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__teaser';
  }
}
