<?php
/**
 * @file
 * A module defining custom functionality for the Pivot.tv website
 *
 */
/**
 * Implements hook_help();
 */
function pivot_global_help($path, $arg) {
    if ($path == 'admin/help#pivot_global') {
        return t('A module defining custom functionality for the Pivot.tv website');
    }
}
/**
 * Define custom blocks for the Pivot.tv site
 */
module_load_include('inc', 'pivot_global', 'pivot_global.blocks');
module_load_include('inc', 'pivot_global', 'pivot_global.gallery');

/**
 * Implements hook_menu();
 */
function pivot_global_menu() {
  $items['iframe/header'] = array(
    'page callback' => 'pivot_global_iframe_header',
    'access arguments' => array('access content'),
  );
  $items['iframe/footer'] = array(
    'page callback' => 'pivot_global_iframe_footer',
    'access arguments' => array('access content'),
  );
  return $items;
}


/**
* Implements hook_entity_info_alter().
*/
function pivot_global_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['promo'] = array(
    'label' => t('Square Promo'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['promo_alt'] = array(
    'label' => t('16x9 Promo'),
    'custom settings' => TRUE,
  );
}

/**
* Prevent Drupal from checking for updates on custom created modules
**/
function pivot_global_update_projects_alter(&$projects) {
  unset($projects['pivot_global']);
  unset($projects['pivot_campaign']);
  unset($projects['pivot_hero']);
  unset($projects['pivot_dml']);
}

function pivot_global_iframe_header(){
  $output = 'something';
  return $output;
}
function pivot_global_iframe_footer(){
  $output = 'something';
  return $output;
}

