<?php


function pivot_campaign_menu() {

  $items['admin/config/campaign'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pivot_campaign_config'),
    'access arguments' => array('administer nodes'),
  );

  return $items;
}


 function pivot_campaign_config(){
  $form['pivot_campaign_path'] = array(
    '#type' => 'form',
    '#title' => t('Campaign Config'),
    '#description' => t("Path with no leading or trailing slash.  Example 'campaign/dml"),
  );

  $form = system_settings_form($form);
  return $form;
}


 function pivot_campaign_block_info(){
  $blocks = array();
  $blocks['pivot_campaign_hero'] = array(
    'info' => t('Hero Menu')
   );
  return $blocks;
 }


function pivot_campaign_block_view(){
  //The $delta parameter tells us which block is being requested.
  $block = array();
  switch ($delta) {
    case 'pivot_campaign_hero':
      $block['content'] = pivot_campaign_hero();
      break;
  }
  return $block;
  }

function pivot_campaign_hero() {
  // dpm(get_defined_vars(), 'defined vars');
}










