<?php

/**
 * @file
 * Main file for the Pivot Contact Us custom module.
 */

/**
 * Implement hook_form_FORM_ID_alter
 *
 */
function pivot_contact_us_form_zendesk_forms_support_form_alter(&$form, &$form_state, $form_id) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#required' => TRUE,
    );
    $form['requester'] = array(
        '#type' => 'textfield',
        '#title' => t('Email address'),
        '#required' => TRUE,
    );
    $form['subject'] = array(
        '#type' => 'textfield',
        '#title' => t('Subject'),
        '#required' => TRUE,
        '#maxlength' => 150,
    );
    $form['description'] = array(
        '#type' => 'textarea',
        '#title' => t('Message'),
        '#required' => TRUE,
        '#maxlength' => 1500,
        '#maxlength_js' => TRUE,
    );
    $form['group_id'] = array(
        '#type' => 'hidden',
        '#value' => 20847042,
    );
    $form['zendesk_23560737'] = array(
        '#type' => 'hidden',
        '#default_value' => '',
    );
    $form['zendesk_23560727'] = array(
        '#type' => 'hidden',
        '#value' => $_SERVER['HTTP_REFERER'],
    );
    $form['zendesk_23643146'] = array(
        '#type' => 'hidden',
        '#value' => variable_get('site_name', ''),
    );
    return $form;
}

function pivot_contact_us_block_info_alter(&$blocks, $theme, $code_blocks) {
    $blocks['zendesk_forms']['zendesk_support_form']['cache'] = DRUPAL_NO_CACHE;
}

function pivot_contact_us_block_view_zendesk_forms_zendesk_support_form_alter(&$data, $block) {
    $form_body = drupal_get_form('zendesk_forms_support_form');
    $js = '<script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery("input[name=zendesk_23560737]").val(navigator.userAgent);
        });
        </script>';
    $data['subject'] = t('');
    $data['content'] = drupal_render($form_body) . "\n" . $js;
}