<?php
/**
 * @file
 * Main file for the Pivot Contact Us custom module.
 */

/**
 * Form to create a ticket with Zendesk.
 *
 * @ingroup forms
 */
function pivot_contact_us_support_form() {
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Your name'),
    '#required' => TRUE,
  );
  $form['requester'] = array(
    '#type' => 'textfield',
    '#title' => t('Your e-mail address'),
    '#required' => TRUE,
  );
  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );
  $form['#attributes'] = array('class' => 'zendesk-support-form');
  return $form;
}

/**
 * Validate the create ticket form.
 *
 * @ingroup forms
 */
function pivot_contact_us_support_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['requester'])) {
    form_set_error('requester', t('Supplied email is not valid'));
  }
}

/**
 * Submit handler for the create ticket form.
 *
 * @ingroup forms
 */
function pivot_contact_us_support_form_submit($form, &$form_state) {
  $ticket = array(
    'description' => $form_state['values']['description'],
    'requester' => array(
      'name' => $form_state['values']['name'],
      'email' => $form_state['values']['requester'],
    ),
  );
  if (!empty($form_state['values']['subject'])) {
    $ticket['subject'] = $form_state['values']['subject'];
  }
  // Get extra fields that are prefixed with zendesk_. Right now the only way
  // to add extra fields is by using form alter though.
  $extra_fields = array_filter(array_keys($form_state['values']), create_function('$item', 'return strpos($item, "zendesk_") === 0;'));
  if (!empty($extra_fields)) {
    foreach ($extra_fields as $field_name) {
      $ticket[substr($field_name, 8)] = $form_state['values'][$field_name];
    }
  }
  // Wrap the ticket array in yet another array and call the API.
  $response = pivot_contact_us_api_call(array('ticket' => $ticket), 'tickets.json');
  if (!isset($response->error)) {
    drupal_set_message(t('Your message has been sent'));
  }
  else {
    drupal_set_message(t('An error happened while sending the message.'), 'error');
  }
}

/**
 * Performs a call to the Zendesk API with the given data.
 *
 * @param array $data
 *   The data to be sent to the API endpoint.
 * @param string $command
 *   The command to call at the endpoint. Will be a filename like "tickets.json"
 * or similar.
 * See http://developer.zendesk.com/documentation/rest_api/tickets.html and
 * https://support.zendesk.com/entries/21562288-Creating-a-Custom-HTML-Form-for-Ticket-Submission
 *
 * @return string
 *   The json response string.
 */
function pivot_contact_us_api_call($data, $command) {
  $json = json_encode($data);
  $zendesk_key = variable_get('pivot_contact_us_api_key', '');
  $zendesk_url = variable_get('pivot_contact_us_url', '');
  $zendesk_user = variable_get('pivot_contact_us_user_name', '');
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
  curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
  curl_setopt($ch, CURLOPT_URL, $zendesk_url . '/api/v2/' . $command);
  curl_setopt($ch, CURLOPT_USERPWD, "$zendesk_user/token:$zendesk_key");
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
  curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-type: application/json'));
  curl_setopt($ch, CURLOPT_USERAGENT, 'MozillaXYZ/1.0');
  curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_TIMEOUT, 10);
  $output = curl_exec($ch);
  curl_close($ch);
  return json_decode($output);
}
