<?php
/**
 * @file
 * TakeAction Button JavaScript Module.
 */

/**
 * Implements hook_init().
 */
function takeaction_javascript_init() {
  $uri = drupal_get_path_alias($_GET['q']);
  if (($uri != 'iframes/header') && ($uri != 'iframes/footer') && ($uri != 'iframes/slim-header')) {
    $button_js_url = variable_get('takeaction_button_js_url', '');
    if (!empty($button_js_url)) {
      $scheme = parse_url($button_js_url, PHP_URL_SCHEME);
      $host = parse_url($button_js_url, PHP_URL_HOST);
      $location = variable_get('takeaction_button_js_location', 'footer');
      $pub_id = variable_get('takeaction_button_pub_id', '');
      $publisher_js = parse_url($button_js_url, PHP_URL_PATH);
      $args = parse_url($button_js_url, PHP_URL_QUERY);
      if (!empty($args)) {
        $publisher_js .= '?' . $args;
      }
      $anchor = parse_url($button_js_url, PHP_URL_FRAGMENT);
      if (!empty($anchor)) {
        $publisher_js .= '#' . $anchor;
      }
      $button_js = "
        window.TP = window.TP || {};
        TP.tabHost = '{$scheme}://{$host}';
        TP.publisherId = '{$pub_id}';
        (function() {
          var tabScript = document.createElement('script');
          tabScript.type = 'text/javascript';
          tabScript.async = true;
          var scriptLocation = TP.tabHost || 'http://takeaction.takepart.com';
          tabScript.src = scriptLocation + '{$publisher_js}';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(tabScript, s);
        })();
      ";
      drupal_add_js($button_js, array(
        'type' => 'inline',
        'group' => JS_LIBRARY,
        'every_page' => TRUE,
        'scope' => $location,
        'weight' => 0,
      ));
    }
  }
}
