<?php

function pivot_hero_field_formatter_info() {
  return array(
    'pivot_hs' => array(
        'label' => t('Homepage Slider Formatter'),
        'field types' => array('file'),
    ),
  );
}

function pivot_hero_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'pivot_hs':
      $element = array(
      '#theme' => 'pivot_hero_format',
      '#items' => $items,
      '#list_style' => 'thumb',
      '#entity_data' => $entity
      );
      break;
  }
  return $element;
}
function pivot_hero_node_view($node, $view_mode) {
  if($node->type == 'homepage_slide' && $view_mode == 'teaser') {

  }
}

function pivot_hero_theme() {
  return array(
    'pivot_hero_format' => array(
        'variables' => array(
            'items' => array(),
            'list_style' => '',
            'entity_data' => NULL
        ),
        'file' => 'pivot_hero.theme.inc'
    ),
  );
}
function pivot_hero_preprocess_page(&$variables) {
  if($variables['is_front'] == TRUE) {
    // drupal_add_js(drupal_get_path('module', 'pivot_hero'). '/js/tpmodal.jquery.js');
    // drupal_add_js(drupal_get_path('module', 'pivot_hero'). '/js/tpslide.jquery.js');
    // drupal_add_js(drupal_get_path('module', 'pivot_hero'). '/js/tpselect.jquery.js');
    // drupal_add_js(drupal_get_path('module', 'pivot_hero'). '/js/pivot-hero-script.js');
  }
  
}
function pivot_hero_preprocess_node(&$variables) {
  if($variables['type'] == 'homepage_slide'){

  }
}



